version: '2'
services:

  # Base services
  s5r-rabbitmq:
    extends:
      file: ./node_modules/sammler-base/docker-compose.yml
      service: 's5r-rabbitmq'

  s5r-scheduler:
    extends:
      file: ./node_modules/sammler-base/docker-compose.yml
      service: 's5r-scheduler'

  # Middleware GitHub
  sammler-middleware-github:
    build: .
    links:
      - s5r-rabbitmq
      - s5r-scheduler

    environment:
      - SAMMLER_MIDDLEWARE_GITHUB_PORT=3010
      - SAMMLER_RABBITMQ_URL=amqp://guest:guest@s5r-rabbitmq:5672
