version: '2'
services:

  sammler-middleware-github-db:
    extends:
      file: ./docker/sammler-middleware-github-db/docker-compose.yml
      service: sammler-middleware-github-db

  sammler-middleware-github:
    build: .
    links:
      - sammler-middleware-github-db

volumes:
  postgres_data:
