version: '2'
services:

  # Base services
  s5r-rabbitmq:
    extends:
      file: ./node_modules/sammler-base/docker-compose.yml
      service: 's5r-rabbitmq'

  s5r-scheduler:
    extends:
      file: ./node_modules/sammler-base/docker-compose.yml
      service: 's5r-scheduler'

  # Middleware GitHub
  sammler-middleware-github-db:
    extends:
      file: ./docker/sammler-middleware-github-db/docker-compose.yml
      service: sammler-middleware-github-db
    links:
      - s5r-scheduler
      - s5r-rabbitmq

  sammler-middleware-github:
    build: .
    links:
      - sammler-middleware-github-db
    environment:
      - SAMMLER_MIDDLEWARE_GITHUB_PORT=3010

  sammler-middleware-github-pgadmin:
    container_name: "sammler-middleware-github-pgadmin"
    image: fenglc/pgadmin4:1.1
    ports:
      - "5050:5050"
    links:
      - sammler-middleware-github-db
      - sammler-middleware-github # wait for the DB to be initialized

  flyway-rest:
    container_name: "sammler-middleware-github-flyway-rest"
    extends:
      file: ./node_modules/flyway-rest/docker/flyway-rest/docker-compose.yml
      service: flyway-rest
    #image: stefanwalther/flyway-rest
    ports:
      - "9001:9001"
    links:
      - sammler-middleware-github-db

volumes:
  postgres_data:
