version: '2'
services:

  sammler_github_db:
    extends:
      file: ./docker/sammler_github_db/docker-compose.yml
      service: sammler_github_db

  sammler_github:
    extends:
      file: ./docker/sammler_github/docker-compose.yml
      service: sammler_github
    links:
      - sammler_github_db
