version: '2'
services:

  sammler_github_db:
    extends:
      file: ./docker/sammler-github-db/docker-compose.yml
      service: sammler-github-db

  sammler_github:
    extends:
      file: ./docker/sammler-github/docker-compose.yml
      service: sammler-github
    links:
      - sammler-github-db
