version: '2'
services:
  github_db:
    container_name: sammler-github-db
    build: ./config/db/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PWD=docker
      - POSTGRES_DB=docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
  flyway-migrator:
    container_name: sammler-github-db-flyway
    build: ./config/flyway
    volumes:
      - ./sql/:/flyway/sql
    depends_on:
      - github_db
    command: sammler-github-db 5432 docker docker docker public migrate
#  api:
#    container_name: sammler-middlware-github
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - .:/data
#    depends_on:
#      - github_db
#      - flyway-migrator
#    links:
#      - github_db
volumes:
  postgres_data:


