version: "2"

services:

  # ----------------------------------------------------------
  # Base services
  # ----------------------------------------------------------
  s5r-rabbitmq:
    extends:
      file: ./node_modules/sammler-base/docker-compose.yml
      service: "s5r-rabbitmq"
    ports:
      - "8080:15672"
      - "5672:5672"

  s5r-mongo:
    extends:
      file: ./node_modules/sammler-base/docker-compose.yml
      service: "s5r-mongo"
    ports:
      - "27017:27017"

  # ----------------------------------------------------------
  # Dependent services
  # ----------------------------------------------------------

  s5r-jobs-service:
    build:
      context: ./node_modules/jobs-service
    environment:
      - PORT=4003
      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://s5r-mongo:27017) = 200 ]
      - WAIT_START_CMD=yarn run start:dev
      - WAIT_SLEEP=2
      - WAIT_LOOPS=20
      - SAMMLER_DB_JOBS_URI=$SAMMLER_DB_JOBS_URI
    volumes:
      - ./node_modules/jobs-service/:/home
    links:
      - s5r-mongo
    command: sh wait_to_start.sh

  # ----------------------------------------------------------
  # Strategies
  # ----------------------------------------------------------


