version: '2'
services:

  sammler-mw-github-db:
    extends:
      file: ./docker/sammler-github-db/docker-compose.yml
      service: sammler-github-db

  sammler-mw-github:
    extends:
      file: ./docker/sammler-middleware-github/docker-compose.yml
      service: sammler-middleware-github
    links:
      - sammler-mw-github-db

volumes:
  postgres_data:
