version: '2'
services:

  sammler-middleware-github:
    context: ./../
    dockerfile: Dockerfile
    links:
      - sammler-middleware-github-db

  sammler-middleware-github-db:
    extends:
      file: ./sammler-github-db/docker-compose.yml
      service: sammler-middleware-github-db

  sammler-middleware-github-pgadmin:
    container_name: "sammler-middelware-github-pgadmin"
    image: fenglc/pgadmin4:1.1
    ports:
      - "5050:5050"
    links:
      - sammler-github-db

  flyway-rest:
    container_name: "sammler-github-flyway-rest"
    extends:
      file: ./../node_modules/flyway-rest/docker/flyway-rest/docker-compose.yml
      service: flyway-rest
    #image: stefanwalther/flyway-rest
    ports:
      - "9001:9001"
    links:
      - sammler-github-db

volumes:
  postgres_data:
