version: '2'
services:

  sammler-github-db:
    extends:
      file: ./sammler-github-db/docker-compose.yml
      service: sammler-github-db

  sammler-middleware-github:
    extends:
      file: ./sammler-middleware-github/docker-compose.yml
      service: sammler-middleware-github
    links:
      - sammler-github-db

#  api:
#    container_name: sammler-middlware-github
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - .:/data
#    depends_on:
#      - github_db
#      - flyway-migrator
#    links:
#      - github_db

volumes:
  postgres_data:


