version: '2'
services:
  sammler_github_db:
    container_name: 'sammler_github_db'
    build: .
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_DB=sammler-github
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
